name: Assignment 14 CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    name: Code Quality (ESLint & Prettier)
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Check Prettier formatting
      run: npm run format:check
      
    - name: Run Prettier fix (if needed)
      run: npm run format
      continue-on-error: true

  test:
    runs-on: ubuntu-latest
    name: Unit Tests & Coverage
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with coverage
      run: npm run test:ci
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    name: Build Production App
    needs: [lint-and-format, test]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build production app
      run: npm run build
      
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: build/
        retention-days: 7

  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build & Test
    needs: [build]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build -t lu_luke_coding_assignment14 .
      
    - name: Test Docker container
      run: |
        docker run -d -p 5575:5575 --name test-container lu_luke_coding_assignment14
        sleep 10
        curl -f http://localhost:5575 || exit 1
        docker stop test-container
        docker rm test-container

  deployment-ready:
    runs-on: ubuntu-latest
    name: Deployment Validation
    needs: [docker-build]
    
    steps:
    - name: Deployment Success
      run: |
        echo "🎉 Assignment 14 Portfolio is ready for deployment!"
        echo "✅ All quality checks passed"
        echo "✅ Tests completed successfully"
        echo "✅ Docker container builds and runs"
        echo "🚀 Ready for submission at localhost:5575"
